included:
  - App/Tymark
  - Packages
excluded:
  - .build
  - Packages/**/Tests
  - Packages/**/Resources

disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - todo

reporter: "github-actions-logging"
